apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: deployment-service-pdb
  namespace: hse-llm-project
spec:
  maxUnavailable: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: deployment-service
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: security-audit-service-pdb
  namespace: hse-llm-project
spec:
  maxUnavailable: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: security-audit-service
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: llmdeployment-controller-pdb
  namespace: hse-llm-project
spec:
  maxUnavailable: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: llmdeployment-vllm-controller

