apiVersion: v1
kind: ConfigMap
metadata:
  name: external-coredns
  namespace: kube-system
  labels:
    app.kubernetes.io/name: external-coredns
    app.kubernetes.io/component: dns-authoritative
    app.kubernetes.io/managed-by: dns-pipeline
data:
  Corefile: |
    .:53 {
        log
        errors
        health
        ready
        etcd hse-llm-project-2026.ru {
            path /skydns
            endpoint http://dns-etcd.kube-system.svc.cluster.local:2379
        }
        forward . 8.8.8.8
        cache 30
        loadbalance
    }
