apiVersion: v1
kind: PersistentVolume
metadata:
  name: gitlab-demo-data-pv
  labels:
    app.kubernetes.io/name: gitlab-demo
spec:
  capacity:
    storage: 120Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: ""
  hostPath:
    path: /var/lib/gitlab-demo-v2
    type: DirectoryOrCreate
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - worker-1
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: gitlab-demo-data
  namespace: gitlab-demo
  labels:
    app.kubernetes.io/name: gitlab-demo
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 120Gi
  storageClassName: ""
  volumeName: gitlab-demo-data-pv
