apiVersion: v1
kind: Secret
metadata:
  name: gitlab-root-secret
  namespace: gitlab-demo
  labels:
    app.kubernetes.io/name: gitlab-demo
type: Opaque
stringData:
  password: "ChangeMe_GitLabRoot_12345"
